tweebank_labels_to_ids = {
    'PUNCT' : 0, 
    'NUM' : 1, 
    'VERB' : 2, 
    'DET' : 3, 
    'PROPN' : 4, 
    'PRON' : 5, 
    'ADJ' : 6, 
    'ADP' : 7, 
    'SYM' : 8, 
    'CCONJ' : 9, 
    'NOUN' : 10, 
    'INTJ' : 11, 
    'AUX' : 12, 
    'PART' : 13, 
    'ADV' : 14, 
    'SCONJ' : 15,
    'X' : 16,
}


tweebank_ids_to_labels = {
    0 : 'PUNCT', 
    1 : 'NUM', 
    2 : 'VERB', 
    3 : 'DET', 
    4 : 'PROPN', 
    5 : 'PRON', 
    6 : 'ADJ', 
    7 : 'ADP', 
    8 : 'SYM', 
    9 : 'CCONJ', 
    10 : 'NOUN', 
    11 : 'INTJ', 
    12 : 'AUX', 
    13 : 'PART', 
    14 : 'ADV', 
    15 : 'SCONJ',
    16 : 'X',
}